config/routes.rb
Rails.application.routes.draw do
  resources :sub_requirements
  resources :requirements
  resources :ranks
  resources :advancements
  get 'view' => 'advancements#view'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/requirement.rb
class Requirement < ApplicationRecord
  belongs_to :rank
  has_many :sub_requirements
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  before_action :set_requirement, only: [:show, :edit, :update, :destroy]

  # GET /requirements
  # GET /requirements.json
  def index
    @requirements = Requirement.all
  end

  # GET /requirements/1
  # GET /requirements/1.json
  def show
  end

  # GET /requirements/new
  def new
    @requirement = Requirement.new
  end

  # GET /requirements/1/edit
  def edit
  end

  # POST /requirements
  # POST /requirements.json
  def create
    @requirement = Requirement.new(requirement_params)

    respond_to do |format|
      if @requirement.save
        format.html { redirect_to @requirement, notice: 'Requirement was successfully created.' }
        format.json { render :show, status: :created, location: @requirement }
      else
        format.html { render :new }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requirements/1
  # PATCH/PUT /requirements/1.json
  def update
    respond_to do |format|
      if @requirement.update(requirement_params)
        format.html { redirect_to @requirement, notice: 'Requirement was successfully updated.' }
        format.json { render :show, status: :ok, location: @requirement }
      else
        format.html { render :edit }
        format.json { render json: @requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requirements/1
  # DELETE /requirements/1.json
  def destroy
    @requirement.destroy
    respond_to do |format|
      format.html { redirect_to requirements_url, notice: 'Requirement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requirement
      @requirement = Requirement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def requirement_params
      params.require(:requirement).permit(:number, :description, :completed, :rank_id)
    end
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/views/requirements/_form.html.erb
<%= form_for(requirement) do |f| %>
  <% if requirement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(requirement.errors.count, "error") %> prohibited this requirement from being saved:</h2>

      <ul>
      <% requirement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %>
    <%= f.number_field :number %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :completed %>
    <%= f.date_select :completed %>
  </div>

  <div class="field">
    <%= f.label :rank_id %>
    <%= f.number_field :rank_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/requirements/edit.html.erb
<h1>Editing Requirement</h1>

<%= render 'form', requirement: @requirement %>

<%= link_to 'Show', @requirement %> |
<%= link_to 'Back', requirements_path %>

app/views/requirements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Requirements</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Description</th>
      <th>Completed</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requirements.each do |requirement| %>
      <tr>
        <td><%= requirement.number %></td>
        <td><%= requirement.description %></td>
        <td><%= requirement.completed %></td>
        <td><%= requirement.rank_id %></td>
        <td><%= link_to 'Show', requirement %></td>
        <td><%= link_to 'Edit', edit_requirement_path(requirement) %></td>
        <td><%= link_to 'Destroy', requirement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Requirement', new_requirement_path %>

app/views/requirements/new.html.erb
<h1>New Requirement</h1>

<%= render 'form', requirement: @requirement %>

<%= link_to 'Back', requirements_path %>

app/views/requirements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @requirement.number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @requirement.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @requirement.completed %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @requirement.rank_id %>
</p>

<%= link_to 'Edit', edit_requirement_path(@requirement) %> |
<%= link_to 'Back', requirements_path %>