config/routes.rb
Rails.application.routes.draw do
  resources :sub_requirements
  resources :requirements
  resources :ranks
  resources :advancements
  get 'view' => 'advancements#view'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/rank.rb
class Rank < ApplicationRecord
  belongs_to :advancement
  has_many :requirements
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :set_rank, only: [:show, :edit, :update, :destroy]

  # GET /ranks
  # GET /ranks.json
  def index
    @ranks = Rank.all
  end

  # GET /ranks/1
  # GET /ranks/1.json
  def show
  end

  # GET /ranks/new
  def new
    @rank = Rank.new
  end

  # GET /ranks/1/edit
  def edit
  end

  # POST /ranks
  # POST /ranks.json
  def create
    @rank = Rank.new(rank_params)

    respond_to do |format|
      if @rank.save
        format.html { redirect_to @rank, notice: 'Rank was successfully created.' }
        format.json { render :show, status: :created, location: @rank }
      else
        format.html { render :new }
        format.json { render json: @rank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ranks/1
  # PATCH/PUT /ranks/1.json
  def update
    respond_to do |format|
      if @rank.update(rank_params)
        format.html { redirect_to @rank, notice: 'Rank was successfully updated.' }
        format.json { render :show, status: :ok, location: @rank }
      else
        format.html { render :edit }
        format.json { render json: @rank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ranks/1
  # DELETE /ranks/1.json
  def destroy
    @rank.destroy
    respond_to do |format|
      format.html { redirect_to ranks_url, notice: 'Rank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rank
      @rank = Rank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rank_params
      params.require(:rank).permit(:name, :description, :completed, :advancement_id)
    end
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/views/ranks/_form.html.erb
<%= form_for(rank) do |f| %>
  <% if rank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rank.errors.count, "error") %> prohibited this rank from being saved:</h2>

      <ul>
      <% rank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :completed %>
    <%= f.date_select :completed %>
  </div>

  <div class="field">
    <%= f.label :advancement_id %>
    <%= f.number_field :advancement_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ranks/edit.html.erb
<h1>Editing Rank</h1>

<%= render 'form', rank: @rank %>

<%= link_to 'Show', @rank %> |
<%= link_to 'Back', ranks_path %>

app/views/ranks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ranks</h1>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Description</th>
      <th>Completed</th>
      <th>Advancement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ranks.each do |rank| %>
      <tr>
        <td><%= rank.name %></td>
        <td><%= rank.description %></td>
        <td><%= rank.completed %></td>
        <td><%= rank.advancement_id %></td>
        <td><%= link_to 'Show', rank %></td>
        <td><%= link_to 'Edit', edit_rank_path(rank) %></td>
        <td><%= link_to 'Destroy', rank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rank', new_rank_path %>

app/views/ranks/new.html.erb
<h1>New Rank</h1>

<%= render 'form', rank: @rank %>

<%= link_to 'Back', ranks_path %>

app/views/ranks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rank:</strong>
  <%= @rank.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @rank.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @rank.completed %>
</p>

<p>
  <strong>Advancement:</strong>
  <%= @rank.advancement_id %>
</p>

<%= link_to 'Edit', edit_rank_path(@rank) %> |
<%= link_to 'Back', ranks_path %>