config/routes.rb
Rails.application.routes.draw do
  resources :sub_requirements
  resources :requirements
  resources :ranks
  resources :advancements
  get 'view' => 'advancements#view'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/advancement.rb
class Advancement < ApplicationRecord
  belongs_to :user
  has_many :ranks
end

app/controllers/advancements_controller.rb
class AdvancementsController < ApplicationController
  before_action :set_advancement, only: [:show, :edit, :update, :destroy]

  def view
      @advancements = Advancement.find_by(user_id: current_user.id)
      @ranks = @advancements.ranks
  end
  # GET /advancements
  # GET /advancements.json
  def index
    @advancements = Advancement.all
  end

  # GET /advancements/1
  # GET /advancements/1.json
  def show
  end

  # GET /advancements/new
  def new
    @advancement = Advancement.new
  end

  # GET /advancements/1/edit
  def edit
  end

  # POST /advancements
  # POST /advancements.json
  def create
    @advancement = Advancement.new(advancement_params)

    respond_to do |format|
      if @advancement.save
        format.html { redirect_to @advancement, notice: 'Advancement was successfully created.' }
        format.json { render :show, status: :created, location: @advancement }
      else
        format.html { render :new }
        format.json { render json: @advancement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advancements/1
  # PATCH/PUT /advancements/1.json
  def update
    respond_to do |format|
      if @advancement.update(advancement_params)
        format.html { redirect_to @advancement, notice: 'Advancement was successfully updated.' }
        format.json { render :show, status: :ok, location: @advancement }
      else
        format.html { render :edit }
        format.json { render json: @advancement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advancements/1
  # DELETE /advancements/1.json
  def destroy
    @advancement.destroy
    respond_to do |format|
      format.html { redirect_to advancements_url, notice: 'Advancement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advancement
      @advancement = Advancement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advancement_params
      params.require(:advancement).permit(:user_id)
    end
end

app/helpers/advancements_helper.rb
module AdvancementsHelper
end

app/views/advancements/_form.html.erb
<%= form_for(advancement) do |f| %>
  <% if advancement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advancement.errors.count, "error") %> prohibited this advancement from being saved:</h2>

      <ul>
      <% advancement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advancements/edit.html.erb
<h1>Editing Advancement</h1>

<%= render 'form', advancement: @advancement %>

<%= link_to 'Show', @advancement %> |
<%= link_to 'Back', advancements_path %>

app/views/advancements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Advancements</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advancements.each do |advancement| %>
      <tr>
        <td><%= advancement.user_id %></td>
        <td><%= link_to 'Show', advancement %></td>
        <td><%= link_to 'Edit', edit_advancement_path(advancement) %></td>
        <td><%= link_to 'Destroy', advancement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advancement', new_advancement_path %>

app/views/advancements/new.html.erb
<h1>New Advancement</h1>

<%= render 'form', advancement: @advancement %>

<%= link_to 'Back', advancements_path %>

app/views/advancements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @advancement.user_id %>
</p>

<%= link_to 'Edit', edit_advancement_path(@advancement) %> |
<%= link_to 'Back', advancements_path %>

app/views/advancements/view.html.erb
<div class="container">
    <h1 class="text-center">Advancements View</h1>
    <h1 class="text-center">Active rank: <%= @advancements.ranks[0].description %></h1>
    <div class="row">
        <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
            <ul class="nav nav-tabs">
                <li><a href="#">Scout</a></li>
                <li><a href="#">Tenderfoot</a></li>
                <li><a href="#">Second Class</a></li>
                <li><a href="#">First Class</a></li>
                <li><a href="#">Star</a></li>
                <li><a href="#">Life</a></li>
                <li><a href="#">Eagle</a></li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
            <div class="table-responsive">
                <table class="table">
                    <tr>
                        <th>#</th>
                        <th>Part</th>
                        <th>Description</th>
                        <th>Complete</th>
                        <th>Date</th>
                    </tr>
                    <% @ranks[0].requirements.each do |requirement| %>
                    <tr>
                        <td><%= requirement.number %></td>
                        <td><%= requirement.part %></td>
                        <td><%= requirement.description %></td>
                        <td></td>
                        <td><%= requirement.completed %></td>
                    </tr>
                    <% end %>
                </table>
            </div>
        </div>
    </div>
</div>