config/routes.rb
Rails.application.routes.draw do
  resources :sub_requirements
  resources :requirements
  resources :ranks
  resources :advancements
  get 'view' => 'advancements#view'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/sub_requirement.rb
class SubRequirement < ApplicationRecord
    belongs_to :requirement
end

app/controllers/sub_requirements_controller.rb
class SubRequirementsController < ApplicationController
  before_action :set_sub_requirement, only: [:show, :edit, :update, :destroy]

  # GET /sub_requirements
  # GET /sub_requirements.json
  def index
    @sub_requirements = SubRequirement.all
  end

  # GET /sub_requirements/1
  # GET /sub_requirements/1.json
  def show
  end

  # GET /sub_requirements/new
  def new
    @sub_requirement = SubRequirement.new
  end

  # GET /sub_requirements/1/edit
  def edit
  end

  # POST /sub_requirements
  # POST /sub_requirements.json
  def create
    @sub_requirement = SubRequirement.new(sub_requirement_params)

    respond_to do |format|
      if @sub_requirement.save
        format.html { redirect_to @sub_requirement, notice: 'Sub requirement was successfully created.' }
        format.json { render :show, status: :created, location: @sub_requirement }
      else
        format.html { render :new }
        format.json { render json: @sub_requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_requirements/1
  # PATCH/PUT /sub_requirements/1.json
  def update
    respond_to do |format|
      if @sub_requirement.update(sub_requirement_params)
        format.html { redirect_to @sub_requirement, notice: 'Sub requirement was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_requirement }
      else
        format.html { render :edit }
        format.json { render json: @sub_requirement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_requirements/1
  # DELETE /sub_requirements/1.json
  def destroy
    @sub_requirement.destroy
    respond_to do |format|
      format.html { redirect_to sub_requirements_url, notice: 'Sub requirement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_requirement
      @sub_requirement = SubRequirement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_requirement_params
      params.require(:sub_requirement).permit(:requirement_id, :part, :description)
    end
end

app/helpers/sub_requirements_helper.rb
module SubRequirementsHelper
end

app/views/sub_requirements/_form.html.erb
<%= form_for(sub_requirement) do |f| %>
  <% if sub_requirement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_requirement.errors.count, "error") %> prohibited this sub_requirement from being saved:</h2>

      <ul>
      <% sub_requirement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :requirement_id %>
    <%= f.number_field :requirement_id %>
  </div>

  <div class="field">
    <%= f.label :part %>
    <%= f.text_field :part %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sub_requirements/edit.html.erb
<h1>Editing Sub Requirement</h1>

<%= render 'form', sub_requirement: @sub_requirement %>

<%= link_to 'Show', @sub_requirement %> |
<%= link_to 'Back', sub_requirements_path %>

app/views/sub_requirements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Requirements</h1>

<table>
  <thead>
    <tr>
      <th>Requirement</th>
      <th>Part</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_requirements.each do |sub_requirement| %>
      <tr>
        <td><%= sub_requirement.requirement_id %></td>
        <td><%= sub_requirement.part %></td>
        <td><%= sub_requirement.description %></td>
        <td><%= link_to 'Show', sub_requirement %></td>
        <td><%= link_to 'Edit', edit_sub_requirement_path(sub_requirement) %></td>
        <td><%= link_to 'Destroy', sub_requirement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Requirement', new_sub_requirement_path %>

app/views/sub_requirements/new.html.erb
<h1>New Sub Requirement</h1>

<%= render 'form', sub_requirement: @sub_requirement %>

<%= link_to 'Back', sub_requirements_path %>

app/views/sub_requirements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Requirement:</strong>
  <%= @sub_requirement.requirement_id %>
</p>

<p>
  <strong>Part:</strong>
  <%= @sub_requirement.part %>
</p>

<p>
  <strong>Description:</strong>
  <%= @sub_requirement.description %>
</p>

<%= link_to 'Edit', edit_sub_requirement_path(@sub_requirement) %> |
<%= link_to 'Back', sub_requirements_path %>